# Config stuff
title: Michael Safarty
description: Michael Safarty, assessment/property appraisal for taxation, fun coding blog? Hopefully, at least.

# Build settings
markdown: kramdown
theme: minima
