# Config stuff
title: Musings
description: Michael Safarty, assessment/property appraisal for taxation, fun coding blog? Hopefully, at least.
baseurl: "blog"
url: ""

# Build settings
markdown: kramdown
theme: minima
